### ISSUE TITLE
Foobillardplus segfault 

### ISSUE THREAD

**Issue by petevine** [lunixbochs/glshim#143]
Using the `restart game` menu option leads to the following crash in foobillardplus triggered by both the master branch and ptitseb's fork:

````
Program received signal SIGSEGV, Segmentation fault.
0xb6788862 in __GI___pthread_mutex_lock (mutex=0x28) at pthread_mutex_lock.c:66
66      pthread_mutex_lock.c: No such file or directory.
(gdb)  bt
#0  0xb6788862 in __GI___pthread_mutex_lock (mutex=0x28) at pthread_mutex_lock.c:66
#1  0xb6bbd43c in XrmDestroyDatabase () from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#2  0xb6badfe4 in _XFreeDisplayStructure () from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#3  0xb6ba32bc in XCloseDisplay () from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#4  0xb6d8860e in ?? () from /usr/lib/arm-linux-gnueabihf/libSDL-1.2.so.0
````

The crash doesn't happen in mesa.

**Comment by MagaTailor** [comment]
Hmm, was I able to see the menu back then? Nowadays it's a much shorter affair:

```
Initialize fire lists completed
Graphic meshes initialized
Run into game loop

Program received signal SIGSEGV, Segmentation fault.
0xb6f5d73c in tack_get (stack=stack@entry=0x138d36c, idx=idx@entry=0)
    at /glshim/src/util/tack.c:87
87          return stack->data[idx];
(gdb) bt
#0  0xb6f5d73c in tack_get (stack=stack@entry=0x138d36c, idx=idx@entry=0)
    at /glshim/src/util/tack.c:87
#1  0xb6f4753c in dl_call (dl=0x138d368) at /glshim/src/gl/list.c:62
#2  0xb6f49360 in glCallList (list=92) at /glshim/src/gl/gl.c:584
#3  0x0001817e in ?? ()
```

**Comment by lunixbochs** [comment]
#156

**Comment by lunixbochs** [comment]
crash should be fixed in unstable, but menu is blank for me atm
